#23 poc translator
Northeastern-Electric-Racing/Calypso pull request #24
Opened 2023-11-02 16:58 UTC by qubitter

2023-11-03 03:19 UTC, Peyton-McKee requested changes
impressive stuff. i find this really interesting code. Just have some clarifying comments and readibility comments

2023-11-03 03:19 UTC, Peyton-McKee commented on oxy/poc_translator.py
> +function_name: str = "decode" + "_" + "_".join(data['string'].split(" "))
why not just “decode_” + “_”.join(...

2023-11-03 03:19 UTC, Peyton-McKee commented on oxy/poc_translator.py
> +    if field["size"] > 1: # we need to do some decoding, then
size = field[“size”]

2023-11-03 03:19 UTC, Peyton-McKee commented on oxy/poc_translator.py
> +        _cf: str = field.get("correcting_factor", "")
correcting_factor_value =

2023-11-03 03:19 UTC, Peyton-McKee commented on oxy/poc_translator.py
> +        correcting_factor: str = f"{(' / ' if '/' in _cf else ' * ') if _cf else ''}{_cf.split('/')[-1]}"
oh yikes. yeah ok we need to do correcting_factor_op and correcting_factor_value in the yaml. Not this

2023-11-03 03:19 UTC, Peyton-McKee commented on oxy/poc_translator.py
> +signature: str = "pub fn " + function_name + args + returnVal + " {"
this is so funny.

2023-11-03 03:19 UTC, Peyton-McKee commented on oxy/poc_translator.py
> +                    case "twos_complement":
lots more cases but yes

2023-11-03 03:19 UTC, Peyton-McKee commented on oxy/poc_translator.py
> +            decodingsetup: dict[str, dict[str, str]] = {k: reduce(lambda x,y: x|y, v, {}) for k,v in decodingsetup.items()}
sure but this is not readable so u either need to add a comment saying what this is doing or rename variables

2023-11-03 03:19 UTC, Peyton-McKee commented on oxy/poc_translator.py
> +                        to_decode = f"pd::big_endian({to_decode}, {params['bits']}) as {params['final_type']}"
outside of the match assign bits = params[‘bits’] and final_type = params[‘final_type’]

2023-11-03 03:19 UTC, Peyton-McKee commented on oxy/poc_translator.py
> +                    case "big_endian":
also if ur gonna do this just u dont even need the match technically just do f”pd::{decoder}({to_decode}, {bits}) {final_type}

2023-11-03 03:19 UTC, Peyton-McKee commented on oxy/poc_translator.py
> +                    case "big_endian":
just rename function names to match this in the rust code

2023-11-03 03:19 UTC, Peyton-McKee commented on oxy/poc_translator.py
> +                    case "big_endian":
or change yaml to match function names

2023-11-04 19:20 UTC, nwdepatie commented
Uh really quick it looks like your making a PR from your local main to remote main, typically we use remote branches so that other devs can easily checkout and verify code. Please make a remote branch and push to that to make a PR

2023-11-04 19:35 UTC, nwdepatie requested changes
Definitely a good start, but please consider scalability and readability in your design. I haven't tried running it so I am assuming you tested it locally and that it can generate code that compiles, but the way you are representing data is a bit lacking, and you didn't use any functions or classes to encapsulate functionality. This results in a lot of nested loops and global variables, in addition to not having a central entry point per regular python stuff. Definitely add in a main function via `if __name__ == "main"` or whatever I forget off the top of my head, and at least make a `YAMLParser` class and a `RustGenerator` class that passes around `CanMsg` objects. I think this is very much an object oriented problem and there is a lot of room to fuck around with some cool data types

2023-11-04 19:35 UTC, nwdepatie commented on oxy/mapping.yaml
> +1:
I think we def need to think about how we structure this YAML. It functions as a source of truth of CAN messages on the car and should therefore be extremely human readable and parseable, such that any engineer can look through. I think as we expand, we need to consider both directory structure for within this repo as well as how the actual file is structured. How _most_ companies do this is that they have a ginormous doc of all messages to fully document the protocol (Amazon did this) or have a really big C file that everything includes that defines types (saw this at SimpliSafe, which is the way I originally tried to implement this stuff). TLDR this  is a very important topic to think about moving forward and should not be glossed over

2023-11-04 19:35 UTC, nwdepatie commented on oxy/poc_translator.py
> +pub fn decode_accumulator_status(data: &[u8]) -> HashMap<u8, f32> {
I'd assume it is a sample function that would be generated, but yeah definitely make that more explicit

2023-11-04 19:35 UTC, nwdepatie commented on oxy/poc_translator.py
> +'''
Right off the bat this whole thing should be encapsulated in a class. I think there is a much better way of structuring this program around objects that would make it all easier to read and understand

2023-11-04 19:35 UTC, nwdepatie commented on oxy/poc_translator.py
> +                    case "big_endian":
This feels like too many indents, def think about splitting into functions to make this more readable. See above comment on classes to encapsulate logic.

2023-11-04 19:35 UTC, nwdepatie commented on oxy/poc_translator.py
> +data = yaml.load(open("mapping.yaml"))[1]
So per the nature of YAML and kinda this general application, I think that you should really think about the data structures going into this. The problem feels a lot like it is parsing a bunch of very similar handlers that are all _slightly_ different, meaning you can probably have a class or something per attribute of the handler. Probably also want to create a "CAN message" class that contains all the attributes associated with a CAN message found in the YAML and then use that to pass to a general decoder.

2023-11-04 19:35 UTC, nwdepatie commented on oxy/poc_translator.py
> +conclusion: str = "    result\n}"
Similar to the comment on using classes to represent the data in the YAML file, I think each component of the rust code would def benefit from putting it into a class.

2023-11-15 05:16 UTC, qubitter commented
Closing to rephrase as a new branch, instead (yay, git)

2023-11-15 05:16 UTC, closed without merging